name: hacker_news
description: Discover the latest news.

version: 1.0.0+1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  test: ^1.9.4


  cupertino_icons: ^0.1.2
  font_awesome_flutter: ^8.5.0

  url_launcher: ^5.3.0
  intl: ^0.16.0
  http: ^0.12.0+2
  rxdart: ^0.23.1
  built_value: ^7.0.0
  built_collection: ^4.3.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.7.2
  built_value_generator: ^7.0.0





flutter:


  uses-material-design: true

  # assets:
  #  - images/a_dot_burr.jpeg


  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro